dist: xenial
language: python
python:
  - "3.7"

install:
  - pip install coverage
  - pip install green codecov
  - pip install .

script:
  - coverage run --source metabolabpy setup.py test

after_script:
  - python -m codecov
