dist: xenial
language: python
python:
  - "3.7"

install:
  - pip install coverage
  - pip install green codecov
  - pip install .

script:
  - green -vvv --run-coverage

after_script:
  - python -m codecov
