environment:
  matrix:
    - PYTHON: "C:\\Python39-x64"
      PYTHON_ARCH: "64"

build_script:
  - '%PYTHON%\python.exe -m pip install .'

before_test:
  - '%PYTHON%\python.exe -m pip install pytest'

test_script:
  - '%PYTHON%\python.exe -m pytest'
