#!/bin/zsh

#conda activate metabolabpy

appify $(which metabolabpy) MetaboLabPy
cp -r mlStarter/Contents MetaboLabPy.app
cp mlStarter/Icon MetaboLabPy.app/Icon$'\r'

mv MetaboLabPy.app /Applications
